name: Android Release Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.4
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Show Gradle version
        run: ./gradlew --version
      
      - name: Build APK with detailed logging
        run: ./gradlew assembleProductionDebug --info
        
      - name: List APK directory
        run: find app/build/outputs -name "*.apk" | sort