name: Android Release Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Check for gradle wrapper jar
        run: |
          if [ ! -f ./gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Gradle wrapper JAR is missing. Creating directory if needed."
            mkdir -p ./gradle/wrapper/
            echo "Downloading Gradle wrapper JAR..."
            curl -L -o ./gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v7.2.0/gradle/wrapper/gradle-wrapper.jar
          fi
          
      - name: Verify gradlew can run
        run: |
          ./gradlew -v || echo "Gradle wrapper version check failed, but continuing"
          
      - name: Use Gradle directly instead of wrapper
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.2
          
      - name: Clean with Gradle
        run: gradle clean
        
      - name: Debug project structure
        run: |
          echo "Current directory structure:"
          find . -type f -name "*.java" | sort
          echo "\nGradle files:"
          find . -name "*.gradle" | sort
          echo "\nManifest file:"
          find . -name "AndroidManifest.xml" | sort
      
      - name: Build with Gradle
        run: gradle assembleProductionDebug --info --stacktrace
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: tixelcheck-debug
          path: app/build/outputs/apk/production/debug/app-production-debug*.apk
          if-no-files-found: warn
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: TixelCheck v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/production/debug/app-production-debug*.apk
          body: |
            ## TixelCheck v1.0.${{ github.run_number }}
            
            **New in this version:**
            - Improved performance
            - Bug fixes
            - Enhanced reliability
            
            **Installation:**
            1. Download the APK file
            2. Allow installation from unknown sources in your device settings
            3. Install the APK
            
            **Features:**
            - Monitor Tixel ticket pages for availability
            - Customizable checking frequency (1, 2, 5, 10, 30, 60 minutes)
            - Loud alerts when tickets become available
            - Direct link to ticket pages from notifications