name: Android Release Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.4
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean build directory
        run: ./gradlew clean
      
      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEY }}
        run: |
          if [ -n "$ENCODED_KEYSTORE" ]; then
            echo $ENCODED_KEYSTORE | base64 -d > keystore.jks
            echo "Keystore decoded successfully"
          else
            echo "No keystore provided, skipping decoding"
            touch keystore.jks
          fi
      
      - name: Build APK
        run: |
          ./gradlew assembleProductionRelease --stacktrace
        
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: tixelcheck-release
          path: app/build/outputs/apk/production/release/app-production-release*.apk
          if-no-files-found: warn
          
      - name: Generate version info
        id: version
        run: echo "VERSION=$(grep -oP 'versionName "\K[^"]+' app/build/generated/source/buildConfig/production/release/com/example/tixelcheck/BuildConfig.java || echo '1.0.0')" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: TixelCheck v${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/production/release/app-production-release*.apk
          body: |
            ## TixelCheck v${{ steps.version.outputs.VERSION }}
            
            **New in this version:**
            - Improved performance
            - Bug fixes
            - Enhanced reliability
            
            **Installation:**
            1. Download the APK file
            2. Allow installation from unknown sources in your device settings
            3. Install the APK
            
            **Features:**
            - Monitor Tixel ticket pages for availability
            - Customizable checking frequency (1, 2, 5, 10, 30, 60 minutes)
            - Loud alerts when tickets become available
            - Direct link to ticket pages from notifications