name: Regenerate Gradle Wrapper

on:
  workflow_dispatch:  # This allows manual triggering from the GitHub UI
  pull_request:
    paths:
      - "gradle/wrapper/gradle-wrapper.properties"  # Trigger when this file changes

jobs:
  regenerate-wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly allow writing to repository contents
      pull-requests: write  # Explicitly allow writing to pull requests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Get Gradle Version from Properties File
        id: gradle_version
        run: |
          if [ -f gradle/wrapper/gradle-wrapper.properties ]; then
            DISTRIBUTION_URL=$(grep distributionUrl gradle/wrapper/gradle-wrapper.properties | cut -d'=' -f2)
            GRADLE_VERSION=$(echo $DISTRIBUTION_URL | grep -o '[0-9]\+\.[0-9]\+')
            echo "GRADLE_VERSION=$GRADLE_VERSION" >> $GITHUB_ENV
            echo "Using Gradle version: $GRADLE_VERSION from properties file"
          else
            echo "GRADLE_VERSION=7.4" >> $GITHUB_ENV
            echo "No gradle-wrapper.properties found, defaulting to Gradle 7.4"
          fi
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          
      - name: Generate Gradle Wrapper using Gradle
        run: |
          # Remove existing wrapper files to ensure clean regeneration
          rm -rf gradle/wrapper
          rm -f gradlew
          rm -f gradlew.bat
          
          # Use Gradle directly to generate the wrapper
          gradle wrapper --gradle-version ${{ env.GRADLE_VERSION }} --distribution-type bin
          
          # Make the wrapper executable
          chmod +x gradlew
          
          # Verify the wrapper works
          ./gradlew --version
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Force-add all files to ensure binary files are included
          git add -f gradle/wrapper/gradle-wrapper.jar
          git add -f gradle/wrapper/gradle-wrapper.properties
          git add -f gradlew
          git add -f gradlew.bat
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Regenerate Gradle wrapper with version ${{ env.GRADLE_VERSION }}"
            git push
            echo "Successfully updated Gradle wrapper files"
          fi