name: Regenerate Gradle Wrapper

on:
  workflow_dispatch:  # This allows manual triggering from the GitHub UI

jobs:
  regenerate-wrapper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Regenerate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 7.4 --distribution-type bin
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add gradle/wrapper/gradle-wrapper.jar
          git add gradle/wrapper/gradle-wrapper.properties
          git add gradlew
          git add gradlew.bat
          git commit -m "Regenerate Gradle wrapper with version 7.4"
          git push
